/**
 * Crawl tracker. Reads the shared `logs` file the variant crawlers append to and,
 * every few seconds, writes human-friendly trackers you can open/tail:
 *
 *   CRAWL-STATUS.md          — a live dashboard (one row per variant)
 *   crawl-logs/<key>.log     — that variant's lines only (de-interleaved)
 *
 * Run in the background alongside the crawlers:
 *   node scripts/track-crawls.mjs &
 * It loops until you stop it (Ctrl-C / kill); it never touches the crawlers.
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const LOG_PATH = join(ROOT, "logs");
const STATUS_PATH = join(ROOT, "CRAWL-STATUS.md");
const OUT_DIR = join(ROOT, "crawl-logs");

// Variant key → log tag + the min-games it was launched with (for display).
const VARIANTS = [
  { key: "horde", tag: "HORDE", min: 65 },
  { key: "atomic", tag: "ATOMIC", min: 85 },
  { key: "racingkings", tag: "RK", min: 35 },
  { key: "antichess", tag: "ANTI", min: 250 },
  { key: "crazyhouse", tag: "ZH", min: 250 },
  { key: "koth", tag: "KOTH", min: 50 },
  { key: "threecheck", tag: "3+", min: 50 },
];

const INTERVAL_MS = 15000;
const PROGRESS_RE =
  /searching… ([\d,]+) positions visited \(net (\d+), cache (\d+)\), ([\d,]+) lines emitted, at depth (\d+), (\d+)s elapsed(?: · ~(\d+)% done)?/;
const COMPLETE_RE =
  /CRAWL COMPLETE in ([\d.]+)s — ([\d,]+) positions .*?([\d,]+) lines emitted, max depth (\d+)/;

function num(s) {
  return s ? Number(String(s).replace(/,/g, "")) : 0;
}

function fmtDur(secs) {
  const s = Math.round(secs);
  const h = Math.floor(s / 3600);
  const m = Math.floor((s % 3600) / 60);
  return h > 0 ? `${h}h${String(m).padStart(2, "0")}m` : `${m}m${String(s % 60).padStart(2, "0")}s`;
}

function rawLineCount(key) {
  const p = join(ROOT, `src/data/${key}-openings.raw.json`);
  if (!existsSync(p)) return null;
  try {
    return JSON.parse(readFileSync(p, "utf8")).length;
  } catch {
    return null;
  }
}

function tick() {
  let allLines = [];
  try {
    allLines = readFileSync(LOG_PATH, "utf8").split("\n").filter(Boolean);
  } catch {
    return; // logs not created yet
  }

  const rows = [];
  for (const v of VARIANTS) {
    const marker = `[${v.tag}]`;
    const lines = allLines.filter((l) => l.includes(marker));
    // Per-variant de-interleaved log file
    try {
      writeFileSync(join(OUT_DIR, `${v.key}.log`), lines.join("\n") + (lines.length ? "\n" : ""));
    } catch {
      /* ignore */
    }

    if (lines.length === 0) {
      rows.push({ ...v, status: "—", positions: 0, emitted: 0, depth: 0, elapsed: 0, pct: null });
      continue;
    }
    const last = lines[lines.length - 1];
    const done = lines.some((l) => l.includes("CRAWL COMPLETE"));
    const interrupted = last.includes("INTERRUPTED");

    let positions = 0;
    let emitted = 0;
    let depth = 0;
    let elapsed = 0;
    let pct = null; // game-weighted % done (null = unknown / old-format line)

    const completeLine = [...lines].reverse().find((l) => COMPLETE_RE.test(l));
    const progressLine = [...lines].reverse().find((l) => PROGRESS_RE.test(l));
    if (done && completeLine) {
      const m = completeLine.match(COMPLETE_RE);
      elapsed = num(m[1]);
      positions = num(m[2]);
      emitted = num(m[3]);
      depth = num(m[4]);
      pct = 100;
    } else if (progressLine) {
      const m = progressLine.match(PROGRESS_RE);
      positions = num(m[1]);
      emitted = num(m[4]);
      depth = num(m[5]);
      elapsed = num(m[6]);
      pct = m[7] !== undefined ? num(m[7]) : null;
    }

    const rawCount = rawLineCount(v.key);
    const status = done
      ? `✅ done${rawCount !== null ? ` (${rawCount} openings)` : ""}`
      : interrupted
      ? "⏸ stopped"
      : "🔄 running";

    rows.push({ ...v, status, positions, emitted, depth, elapsed, pct });
  }

  const now = new Date().toISOString();
  let md = `# Crawl status\n\n_Updated ${now} (auto-refresh every ${INTERVAL_MS / 1000}s; this file is generated by scripts/track-crawls.mjs)._\n\n`;
  md += `| Variant | min-games | status | % done | positions | openings | depth | elapsed |\n`;
  md += `|---|---|---|---|---|---|---|---|\n`;
  for (const r of rows) {
    const pctCell = r.pct === null || r.pct === undefined ? "—" : `${r.pct}%`;
    md += `| ${r.key} | ${r.min} | ${r.status} | ${pctCell} | ${r.positions.toLocaleString()} | ${r.emitted.toLocaleString()} | ${r.depth} | ${fmtDur(r.elapsed)} |\n`;
  }
  md += `\n**Per-variant logs:** \`crawl-logs/<variant>.log\` (de-interleaved from \`logs\`).\n`;
  md += `\nWhen a row shows ✅ done, finalize it: \`node scripts/build-variant-dataset.mjs --variant=<variant>\`.\n`;

  try {
    writeFileSync(STATUS_PATH, md);
  } catch {
    /* ignore */
  }
}

function main() {
  if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });
  console.log(`Tracking crawls → CRAWL-STATUS.md + crawl-logs/*.log (every ${INTERVAL_MS / 1000}s). Ctrl-C to stop.`);
  tick();
  setInterval(tick, INTERVAL_MS);
}

main();
